#!/bin/sh
#/etc/init.d/lightbrite

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  exec forever --sourceDir=/root/lightbrite/nodejs -p /root/lightbrite/nodejs/pidfile app.js
  ;;
stop)
  exec forever stop --sourceDir=/root/lightbrite/nodejs app.js
  ;;
*)
  echo "Usage: /etc/init.d/nodeup {start|stop}"
  exit 1
  ;;
esac

exit 0
